#amazon:
#  associateId: habuma-20
#
#server:
#  port: 8443
#  ssl:
#    key-store: C:/Program Files/Java/jdk1.8.0_73/bin/mykeys.jks
#    key-store-password: letmein
#    key-password: letmein
##spring:
##  thymeleaf:
##    cache: false
##  jpa:
##    hibernate:
##      ddl-auto: create
##    database-platform: H2
##  datasource:
##    url: jdbc:h2:mem:data
## 보통은 JDBC 드라이버를 명시하지 않아도 스프링 부트가 데이터베이스 URL을 보고 판단하지만 문제가 생길경우 명시
##    dbcp:
##      driver-class-name: com.mysql.jdbc.Driver
#logging:
#  level:
#    root: INFO
#    org:
#      springframework:
#      security: DEBUG
#  path: /var/logs
#  file: BookWorm.log


amazon:
  associateId: habuma-20

logging:
  level:
    root: INFO
server:
  port: 0
  jpa:
      database: H2
  datasource:
      url: jdbc:h2:mem:data;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driverClassName: org.h2.Driver
endpoints:
  enabled: false
  metrics:
    enabled: true

---

spring:
  profiles: development

logging:
  level:
    root: DEBUG

